var names = [];
names.push("mukesh", "vishal", "labana"); 
console.log(names);
var str = ["Dylan"];
// str.push("vishal"); 
console.log(str);
var numbers = [1, 2, 3];
numbers.push(4);
var head = numbers[3]; 
console.log(head);
